[package]
name = "validation"
version.workspace = true
edition = "2024"
license.workspace = true

[lints]
workspace = true

[dependencies]
avdschema = { path = "../avdschema", default-features = false }
derive_more = { workspace = true, features = ["display", "from"] }
log = { workspace = true }
ordermap = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = [
    "arbitrary_precision", # To support very big numbers
    "preserve_order",
] }
yaml-parser = { path = "../yaml-parser", default-features = false, features = ["avdschema-core"] }

[features]
default = ["gzip", "regex-perf", "yaml"]
gzip = ["avdschema/gzip"]
regex-perf = ["avdschema/regex-perf"]
yaml = ["avdschema/yaml"]

[lib]
crate-type = ["cdylib", "lib"]
